=== TeamSPoon/old_logicmoo_workspace/prolog/SIRIDUS/UGOT-D31/godis-apps/domain-medical/Database/diseasedb.dtd
<?xml version="1.0" encoding="UTF-8" ?>
<!--
     Structure of a disease database

     NOTE: It isn't clear to me how namespace declaration
     and schema location attributes ought to be defined
     in the DTD. The approach I'm using comes from the
     http://www.w3.org/XML/1998/06/xmlspec-v21.dtd spec
     for the 'xmlns:xlink' attribute.
  -->
<!ELEMENT disease-database
    (#PCDATA|disease|synonyms)*
>
<!ATTLIST disease-database
    xmlns:xsi CDATA #REQUIRED
    xsi:noNamespaceSchemaLocation CDATA #REQUIRED
>
<!--
     disease=(description regions symptoms treatment prevention)
  -->
<!ELEMENT disease
   (#PCDATA|description|regions|symptoms|history|tests|treatment|prevention)*
>
<!ATTLIST disease
    name CDATA #REQUIRED
>
<!--
     A disease description
  -->
<!ELEMENT description
    (#PCDATA)
>
<!--
     A disease's endemic regions
  -->
<!ELEMENT regions
    (#PCDATA)
>
<!--
     A disease's symptoms
  -->
<!ELEMENT symptoms
    (#PCDATA|symptom)*
>
<!ELEMENT symptom
   EMPTY
>
<!ATTLIST symptom
    name CDATA #REQUIRED
    required CDATA #IMPLIED
    present CDATA #IMPLIED
>
<!--
     Relevant medical history items
  -->
<!ELEMENT history
    (#PCDATA|history-item)*
>
<!ELEMENT history-item
   EMPTY
>
<!ATTLIST history-item
    name CDATA #REQUIRED
    required CDATA #IMPLIED
    present CDATA #REQUIRED
>
<!--
     A disease's tests
  -->
<!ELEMENT tests
    (#PCDATA|test)*
>
<!ELEMENT test
   EMPTY
>
<!ATTLIST test
    name CDATA #REQUIRED
    test CDATA #IMPLIED
    result CDATA #IMPLIED
    required CDATA #IMPLIED
    present CDATA #REQUIRED
>
<!--
     Synonyms for symptoms
  -->
<!ELEMENT synonyms
    (#PCDATA|synonym)*
>
<!ELEMENT synonym
   EMPTY
>
<!ATTLIST symptom
    name CDATA #REQUIRED
>
<!--
     A disease's treatment
  -->
<!ELEMENT treatment
    (#PCDATA)
>
<!--
     A disease's prevention
  -->
<!ELEMENT prevention
    (#PCDATA)
>

=== TeamSPoon/old_logicmoo_workspace/pack/logicmoo_nlu/prolog/SIRIDUS/UGOT-D31/godis-apps/domain-medical/Database/diseasedb.xml
<?xml version="1.0" ?>
<!DOCTYPE diseasedb SYSTEM "diseasedb.dtd">
<disease-database>
<disease name="coccidioidomycosis">
<description>
Coccidioidomycosis or "Valley fever" is a disease caused by the fungus Coccidioides immitis, found in the soil of disease-endemic areas. The disease is acquired by inhalation of fungal spores from dust, usually generated by human activities or natural disasters. 

In disease-endemic areas, persons can be at increased risk for disease if they participate in or are present during ground-disturbing activities resulting in exposure to dust. These
outdoor activities include construction, landscaping, mining, agriculture, archaeologic excavation, military maneuvers, and recreational pursuits (e.g., dirt biking). Natural events that result in generation of dust clouds in disease-endemic areas, such as earthquakes or windstorms, increase the risk of infection among exposed persons. 
</description>
<regions>
C. immitis is endemic in regions in the Americas with an arid climate, yearly rainfall 5-20 inches, hot summers, winters with few freezes, and alkaline soils. In the United States, it is found in Arizona, Southern California, New Mexico, Western Texas, and parts of Utah. Outside the United States, coccidioidomycosis is endemic in parts of Argentina, Brazil, Colombia, Guatemala, Honduras, Mexico, Nicaragua, Paraguay, and Venezuela. 
</regions>
<symptoms>
<symptom name="influenzalike illness"/>
<symptom name="headache"/>
<symptom name="muscle aches"/>
<symptom name="dry cough"/>
<symptom name="weight loss"/>
<symptom name="malaise"/>
</symptoms>
<history>
<history-item name="AIDS" required="no"/>
<history-item name="exposure to dust"/>
<history-item name="travel to desert region"/>
</history>
<tests>
<test name="fever" test="CheckFever" result="temperature over 100 degrees"/>
<test name="rash" test="VisualInspection" result="visible rash"/>
</tests>
<treatment>
Most persons with acute symptomatic coccidioidomycosis do not require treatment because the illness is self-limited. 
</treatment>
<prevention>
Although complete prevention of infection is not possible, persons, especially those at increased risk for severe and disseminated disease, can decrease their risk by limiting their exposure to outdoor dust in disease-endemic areas. Dust-control measures include wetting soil before disturbing the earth or using outdoor vehicles with enclosed, air-conditioned cabs. Persons should also be advised to avoid transporting items contaminated with soil (e.g., cotton or straw) from disease-endemic areas because infections have been reported among persons who had never visited the areas but were exposed to such fomites. Wearing well-fitted dust masks capable of filtering particles as small as 0.4 &#x03BC;m can provide  added protection for those at high risk for exposure to dust from disease-endemic areas or those at high risk for severe or disseminated disease. No effective vaccine for coccidioidomycosis is currently available.
</prevention>
</disease>
<disease name="malaria">
<description>
Malaria is a serious, sometimes fatal, disease caused by a parasite. There
 are four kinds of malaria that can infect humans: Plasmodium falciparum
 (plaz-MO-dee-um fal-SIP-a-rum), P. vivax (VI-vacks), P. ovale
 (o-VOL-ley), and P. malariae (ma-LER-ee-aa).

 The World Health Organization estimates that yearly 300-500 million
 cases of malaria occur and more than 1 million people die of malaria.

 Humans get malaria from the bite of a malaria-infected mosquito. When a
 mosquito bites an infected person, it ingests microscopic malaria parasites
 found in the person's blood. The malaria parasite must grow in the
 mosquito for a week or more before infection can be passed to another
 person. If, after a week, the mosquito then bites another person, the
 parasites go from the mosquito's mouth into the person's blood. The
 parasites then travel to the person's liver, enter the liver's cells, grow and
 multiply. During this time when the parasites are in the liver, the person
 has not yet felt sick. The parasites leave the liver and enter red blood
 cells; this may take as little as 8 days or as many as several months. Once
 inside the red blood cells, the parasites grow and multiply. The red blood
 cells burst, freeing the parasites to attack other red blood cells. Toxins
 from the parasite are also released into the blood, making the person feel
 sick. If a mosquito bites this person while the parasites are in his or her
 blood, it will ingest the tiny parasites. After a week or more, the mosquito
 can infect another person.
</description>
<regions>
 Malaria occurs in over 100 countries and territories. More than 40% of
 the people in the world are at risk. Large areas of Central and South
 America, Hispaniola (Haiti and the Dominican Republic), Africa, the
 Indian subcontinent, Southeast Asia, the Middle East, and Oceania are
 considered malaria-risk areas (an area of the world that has malaria).
</regions>
<symptoms>
<symptom name="flu-like illness"/>
<symptom name="chills"/>
<symptom name="headache"/>
<symptom name="muscle aches"/>
<symptom name="tiredness"/>
<symptom name="nausea"/>
<symptom name="vomiting"/>
<symptom name="diarrhea"/>
</symptoms>
<history>
<history-item name="travel outside US"/>
<history-item name="travel to tropical climate"/>
</history>
<tests>
<test name="fever" test="CheckFever" result="temperature over 100 degrees"/>
<test name="shaking" test="VisualInspection" result="visible shaking" required="no"/>
<test name="anemia" test="CBC" result="red blood cell count is very low"/>
<test name="jaundice" test="VisualInspection" result="skin is yellow" required="no"/>
</tests>
<treatment>
Malaria can be cured with prescription drugs. The type of drugs and
 length of treatment depend on which kind of malaria is diagnosed, where
 the patient was infected, the age of the patient, and how severely ill the
 patient was at start of treatment.
</treatment>
<prevention>
Visit your health care provider 4-6 weeks before foreign travel for
 any necessary vaccinations and a prescription for an antimalarial
 drug. 
 Take your antimalarial drug exactly on schedule without missing
 doses. 
 Prevent mosquito and other insect bites. Use DEET insect repellent
 on exposed skin and flying insect spray in the room where you
 sleep. 
 Wear long pants and long-sleeved shirts, especially from dusk to
 dawn. This is the time when mosquitoes that spread malaria bite. 
 Sleep under a mosquito bednet that has been dipped in permethrin
 insecticide if you are not living in screened or air-conditioned
 housing. 
</prevention>
</disease>
<disease name="schistosomiasis">
<description>
Schistosomiasis is caused by flukes, which have complex life cycles involving specific fresh-water snail species as intermediate hosts. Infected snails release large numbers of
minute, free-swimming larvae (cercariae) that are capable of penetrating the unbroken skin of the human host. Even brief exposure to contaminated fresh water, such as wading, swimming, or bathing, can result in infection. Human schistosomiasis cannot be acquired by wading or swimming in salt water (oceans or seas).  
</description>
<regions>
This infection is estimated to occur worldwide, affecting some 200 million persons. Schistosomiasis is most prevalent in sub-Saharan Africa, southern China, the Philippines, and Brazil. 
</regions>
<symptoms>
<symptom name="lack of appetite"/>
<symptom name="weight loss"/>
<symptom name="abdominal pain"/>
<symptom name="weakness"/>
<symptom name="headaches"/>
<symptom name="joint pain"/>
<symptom name="muscle pain"/>
<symptom name="diarrhea"/>
<symptom name="nausea"/>
<symptom name="cough"/>
</symptoms>
<history>
<history-item name="travel outside US"/>
<history-item name="travel to tropical climate"/>
<history-item name="swimming in fresh water"/>
</history>
<tests>
<test name="fever" test="CheckFever" result="temperature over 100 degrees"/>
<test name="hematuria" test="Urinalysis" result="urine contains blood cells"/>
</tests>
<treatment>
Safe and effective oral drugs are available for the treatment of schistosomiasis. Praziquantel is the drug of choice for all species of Schistosoma. Oxamniquine has been effective in treating infections caused by S. mansoni in some areas where praziquantel is less effective. Travelers should be advised to contact an infectious disease or tropical medicine specialist.
</treatment>
<prevention>
No vaccine is available, nor are any drugs recommended as chemoprophylactic agents at this time. Because there is no practical way for the traveler to distinguish infested from
noninfested water, travelers should be advised to avoid fresh-water wading or swimming in rural areas of endemic countries. In such areas, heating bathing water to 50 degrees C (122 degrees F) for 5 minutes or treating it with iodine or chlorine in a manner similar to the precautions recommended for preparing drinking water will destroy cercariae and make the water
safe. Thus, swimming in adequately chlorinated swimming pools is virtually always safe, even in endemic countries. Filtering water with paper coffee filters can also be effective in removing cercariae from bathing water. If these measures are not feasible, travelers should be advised to allow bathing water to stand for 3 days because cercariae rarely survive longer than 48 hours. Vigorous towel drying after accidental exposure to water has been suggested as a way to remove cercariae in the process of skin penetration; however, this may only prevent some infections and should not be recommended to travelers as a preventive measure. 
</prevention>
</disease>
<synonyms>
<synonym name="hematuria"/>
<synonym name="blood in the urine"/>
</synonyms>
<synonyms>
<synonym name="influenzalike illness"/>
<synonym name="flu-like illness"/>
<synonym name="influenza like illness"/>
<synonym name="flu like illness"/>
</synonyms>
<synonyms>
<synonym name="headache"/>
